name: Release and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
        env:
          DEBUG: "release-please*"

      # Паблиш npm только если создан новый релиз
      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: npm ci

      - name: Build all
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: npm run build

      - name: Publish npm-package
        if: ${{ steps.release.outputs.release_created == 'true' }}
        working-directory: ./npm-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
